@startuml
start

if (is Server Adress Empty?) then (yes)
  :Get Server adress from user;
endif

repeat :get list of saved\ngraph from server and\nserve them in pages;
:present user with list\nof saved graphs\nto choose from;
repeat while (search within list or\nchange list's page) is (yes)

fork 
:chose a graph from list;
:Get corresponding json from server;
:check fo version compatibility;
:Set graphdata including graph id and name;
:refresh tree;
fork again
:cancelled;
end fork

stop
@enduml