@startuml
:Key Pressed or button pressed;
if(busy flag is on) then (yes)
    :save current search term in server obj;
    :turn new search falg on;    
    :start 1sec interval timer;
else (no)
    :start new search;
    :turn busy flag on;
    :clear previous search term and flag;
endif
@enduml

@startuml server object states
[*] -> sent
state "waiting for server Response"  as sent 
state "server Response recieved" as recieved
state "timout fired" as fired
recieved: update open file dialog
recieved: check for availability of new request
recieved: uncheck busy flag
recieved: clear search terms
state "new user request" as waiting
waiting: "if server is busy save request\nand start 1sec timer and exit"
sent -> recieved
recieved --> sent
recieved -> waiting
waiting -> sent

fired: get saved url
fired: clear timeout value
fired: clear url
fired --> sent
note "what if server never responds\nfor any of the requests?" as N1
@enduml
