@startuml
state Drawing{
state "Drawing from text" as DrawText
state "Drawing from leaves" as Quiz
}
state "save and retrieve" as CRUD


DrawText: * data is saved to graph_data object
DrawText: * View  change Possible (i.e. to tree or web)

Quiz: * creates new graph_data object\nthat it's leaves is removed
Quiz: * View change possible  (i.e. to tree or web)
Quiz: * When saved it is a subtree\n (structure of current tree)
Quiz: * when Graph loaded, it is temporary

DrawText --> Quiz :make backup of\ngraph_data object
Quiz --> DrawText :restore\n graph_data\n object
Drawing -->CRUD :save\n gngraph_data 
CRUD--> Drawing  :load\n graph_data
@enduml