@startuml model
'#################### Graphdata class ##################
class Graph_Data {
  Dic nodes
  Dic notes

}

'#################### Hierarchy class ##################

class Hierarchy << (G,orchid) >> {

}


    class note << (D,orchid) >> {
        id
        String note
    }
    class node << (D,orchid) >> {
        id
        name
        note_id
        node parent
    }
     


' #################### D3 classes  ##################
class d3
class d3.tree
class Collapsible_Tree
class Radial_Tree
' #################### Links  ##################
d3<|--"d3.tree"
Hierarchy--|>d3
Hierarchy "1" --* "1" Collapsible_Tree
Hierarchy "1" --* "1" Radial_Tree
node "*" --o "1" Hierarchy :Stratified with
"d3.tree" <|-- Collapsible_Tree
"d3.tree" <|-- Radial_Tree
node "1" -- "0.1" note :can have
node "*" --o "1" Graph_Data :has
note "*" --o "1" Graph_Data : has 
'#################### Notes ##################
note "this is a kind of unidirectioal graph\n that holds all of diagram Nodes" as Hierarchy_note
note "stores diagram nodes" as nodes_note
note "stores notes selected notes" as notes_note
Hierarchy_note .. Hierarchy
nodes_note .. node
notes_note .. note
@enduml
